/* Generated By:JavaCC: Do not edit this line. BeagleParserConstants.java */
package beagle.compiler.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface BeagleParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NEWLINE1 = 4;
  /** RegularExpression Id. */
  int IN = 5;
  /** RegularExpression Id. */
  int IF = 6;
  /** RegularExpression Id. */
  int DO = 7;
  /** RegularExpression Id. */
  int FOR = 8;
  /** RegularExpression Id. */
  int TRY = 9;
  /** RegularExpression Id. */
  int NEW = 10;
  /** RegularExpression Id. */
  int PASS = 11;
  /** RegularExpression Id. */
  int ENUM = 12;
  /** RegularExpression Id. */
  int ELIF = 13;
  /** RegularExpression Id. */
  int CASE = 14;
  /** RegularExpression Id. */
  int ELSE = 15;
  /** RegularExpression Id. */
  int TRUE = 16;
  /** RegularExpression Id. */
  int NULL = 17;
  /** RegularExpression Id. */
  int THIS = 18;
  /** RegularExpression Id. */
  int FALSE = 19;
  /** RegularExpression Id. */
  int FINAL = 20;
  /** RegularExpression Id. */
  int CONST = 21;
  /** RegularExpression Id. */
  int SUPER = 22;
  /** RegularExpression Id. */
  int WHILE = 23;
  /** RegularExpression Id. */
  int CATCH = 24;
  /** RegularExpression Id. */
  int BREAK = 25;
  /** RegularExpression Id. */
  int THROW = 26;
  /** RegularExpression Id. */
  int CLASS = 27;
  /** RegularExpression Id. */
  int IMPORT = 28;
  /** RegularExpression Id. */
  int STATIC = 29;
  /** RegularExpression Id. */
  int PUBLIC = 30;
  /** RegularExpression Id. */
  int NATIVE = 31;
  /** RegularExpression Id. */
  int EXPORT = 32;
  /** RegularExpression Id. */
  int SWITCH = 33;
  /** RegularExpression Id. */
  int RETURN = 34;
  /** RegularExpression Id. */
  int ASSERT = 35;
  /** RegularExpression Id. */
  int FINALLY = 36;
  /** RegularExpression Id. */
  int PACKAGE = 37;
  /** RegularExpression Id. */
  int PRIVATE = 38;
  /** RegularExpression Id. */
  int EXTENDS = 39;
  /** RegularExpression Id. */
  int _DEFAULT = 40;
  /** RegularExpression Id. */
  int ABSTRACT = 41;
  /** RegularExpression Id. */
  int READLOCK = 42;
  /** RegularExpression Id. */
  int INTERNAL = 43;
  /** RegularExpression Id. */
  int CONTINUE = 44;
  /** RegularExpression Id. */
  int WRITELOCK = 45;
  /** RegularExpression Id. */
  int PROTECTED = 46;
  /** RegularExpression Id. */
  int INTERFACE = 47;
  /** RegularExpression Id. */
  int INSTANCEOF = 48;
  /** RegularExpression Id. */
  int IMPLEMENTS = 49;
  /** RegularExpression Id. */
  int SYNCHRONIZED = 50;
  /** RegularExpression Id. */
  int LPAREN = 51;
  /** RegularExpression Id. */
  int RPAREN = 52;
  /** RegularExpression Id. */
  int LBRACE = 53;
  /** RegularExpression Id. */
  int RBRACE = 54;
  /** RegularExpression Id. */
  int LBRACKET = 55;
  /** RegularExpression Id. */
  int RBRACKET = 56;
  /** RegularExpression Id. */
  int SEMICOLON = 57;
  /** RegularExpression Id. */
  int COMMA = 58;
  /** RegularExpression Id. */
  int DOT = 59;
  /** RegularExpression Id. */
  int AT = 60;
  /** RegularExpression Id. */
  int ASSIGN = 61;
  /** RegularExpression Id. */
  int MUL = 62;
  /** RegularExpression Id. */
  int DIV = 63;
  /** RegularExpression Id. */
  int BAND = 64;
  /** RegularExpression Id. */
  int BOR = 65;
  /** RegularExpression Id. */
  int XOR = 66;
  /** RegularExpression Id. */
  int REM = 67;
  /** RegularExpression Id. */
  int LT = 68;
  /** RegularExpression Id. */
  int GT = 69;
  /** RegularExpression Id. */
  int BNEG = 70;
  /** RegularExpression Id. */
  int HOOK = 71;
  /** RegularExpression Id. */
  int COLON = 72;
  /** RegularExpression Id. */
  int ADD = 73;
  /** RegularExpression Id. */
  int SUB = 74;
  /** RegularExpression Id. */
  int EQ = 75;
  /** RegularExpression Id. */
  int LE = 76;
  /** RegularExpression Id. */
  int GE = 77;
  /** RegularExpression Id. */
  int NE = 78;
  /** RegularExpression Id. */
  int LOR = 79;
  /** RegularExpression Id. */
  int INCR = 80;
  /** RegularExpression Id. */
  int DECR = 81;
  /** RegularExpression Id. */
  int SHL = 82;
  /** RegularExpression Id. */
  int SHR = 83;
  /** RegularExpression Id. */
  int ASN_ADD = 84;
  /** RegularExpression Id. */
  int ASN_SUB = 85;
  /** RegularExpression Id. */
  int ASN_MUL = 86;
  /** RegularExpression Id. */
  int ASN_DIV = 87;
  /** RegularExpression Id. */
  int ASN_BAND = 88;
  /** RegularExpression Id. */
  int ASN_BOR = 89;
  /** RegularExpression Id. */
  int ASN_XOR = 90;
  /** RegularExpression Id. */
  int ASN_REM = 91;
  /** RegularExpression Id. */
  int VARARG = 92;
  /** RegularExpression Id. */
  int LAND = 93;
  /** RegularExpression Id. */
  int LNEG = 94;
  /** RegularExpression Id. */
  int ASN_SHL = 95;
  /** RegularExpression Id. */
  int ASN_SHR = 96;
  /** RegularExpression Id. */
  int VOID = 97;
  /** RegularExpression Id. */
  int CHAR = 98;
  /** RegularExpression Id. */
  int BYTE = 99;
  /** RegularExpression Id. */
  int SHORT = 100;
  /** RegularExpression Id. */
  int INT = 101;
  /** RegularExpression Id. */
  int LONG = 102;
  /** RegularExpression Id. */
  int FLOAT = 103;
  /** RegularExpression Id. */
  int FIXED = 104;
  /** RegularExpression Id. */
  int DOUBLE = 105;
  /** RegularExpression Id. */
  int BOOLEAN = 106;
  /** RegularExpression Id. */
  int LONG_LITERAL = 107;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 108;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 109;
  /** RegularExpression Id. */
  int HEX_LITERAL = 110;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 111;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 112;
  /** RegularExpression Id. */
  int DECIMAL_FLOATING_POINT_LITERAL = 113;
  /** RegularExpression Id. */
  int DECIMAL_EXPONENT = 114;
  /** RegularExpression Id. */
  int HEXADECIMAL_FLOATING_POINT_LITERAL = 115;
  /** RegularExpression Id. */
  int HEXADECIMAL_EXPONENT = 116;
  /** RegularExpression Id. */
  int CHARACTER_LITERAL = 117;
  /** RegularExpression Id. */
  int STRING_LITERAL = 118;
  /** RegularExpression Id. */
  int IDENTIFIER = 119;
  /** RegularExpression Id. */
  int LETTER = 120;
  /** RegularExpression Id. */
  int PART_LETTER = 121;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "<NEWLINE1>",
    "\"in\"",
    "\"if\"",
    "\"do\"",
    "\"for\"",
    "\"try\"",
    "\"new\"",
    "\"pass\"",
    "\"enum\"",
    "\"elif\"",
    "\"case\"",
    "\"else\"",
    "\"true\"",
    "\"null\"",
    "\"this\"",
    "\"false\"",
    "\"final\"",
    "\"const\"",
    "\"super\"",
    "\"while\"",
    "\"catch\"",
    "\"break\"",
    "\"throw\"",
    "\"class\"",
    "\"import\"",
    "\"static\"",
    "\"public\"",
    "\"native\"",
    "\"export\"",
    "\"switch\"",
    "\"return\"",
    "\"assert\"",
    "\"finally\"",
    "\"package\"",
    "\"private\"",
    "\"extends\"",
    "\"default\"",
    "\"abstract\"",
    "\"readlock\"",
    "\"internal\"",
    "\"continue\"",
    "\"writelock\"",
    "\"protected\"",
    "\"interface\"",
    "\"instanceof\"",
    "\"implements\"",
    "\"synchronized\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"@\"",
    "\"=\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "\"<\"",
    "\">\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"+\"",
    "\"-\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"or\"",
    "\"++\"",
    "\"--\"",
    "\"<<\"",
    "\">>\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"%=\"",
    "\"...\"",
    "\"and\"",
    "\"not\"",
    "\"<<=\"",
    "\">>=\"",
    "\"void\"",
    "\"char\"",
    "\"byte\"",
    "\"short\"",
    "\"int\"",
    "\"long\"",
    "\"float\"",
    "\"fixed\"",
    "\"double\"",
    "\"boolean\"",
    "<LONG_LITERAL>",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<DECIMAL_FLOATING_POINT_LITERAL>",
    "<DECIMAL_EXPONENT>",
    "<HEXADECIMAL_FLOATING_POINT_LITERAL>",
    "<HEXADECIMAL_EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<PART_LETTER>",
    "\"\\u001a\"",
  };

}
